# Generated by Django 3.0.2 on 2020-12-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MontlyReport',
            new_name='MonthlyReport',
        ),
    ]
